In [1]:
import numpy as np 

In [2]:
a = np.array([0, 1, 2])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print(a)

0
1
2
[5 1 2]


In [6]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [9]:
a = np.zeros((3,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [11]:
c = np.full((3,3), 7)
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
d = np.random.random((3,3))
print(d)

[[0.5658447  0.7847811  0.96930344]
 [0.32373226 0.57792127 0.33137996]
 [0.71716245 0.26420363 0.87200245]]


In [16]:

print(np.random.random((3,3)))

[[0.8193103  0.93004604 0.99391115]
 [0.87933259 0.92070251 0.21898745]
 [0.83991204 0.90688567 0.82092038]]


In [17]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [19]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [24]:
i = np.arange(1, 8,dtype=float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [25]:
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [26]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])
z = np.array([5, 6], dtype=np.int64)
print( x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [27]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])

In [28]:
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [32]:
arr[arr>0 ]


array([-1. ,  2. ,  4. ,  4. , -0.5,  6. ,  2.6,  7. ,  8. ,  3. , -7. ,
        4. ,  2. ])

In [39]:
temp = arr[:2, :2:]
temp

array([[-1.],
       [ 4.]])

In [35]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [49]:
x=[[1,2,3],[4,5,6],[7,8,9]]
y=[[10,11,12],[13,14,15],[16,17,18]]
x=np.asanyarray(x)
y=np.asanyarray(y)


print(x+y)
print()
print(x*y)
print()
print(x-y)
print()



[[11 13 15]
 [17 19 21]
 [23 25 27]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]

0


In [54]:
print(x.max(),x.min())
print(y.max(),y.min())

9 1
18 10


In [57]:
x.sum()


45

In [58]:
y.sum()

126

In [69]:
(np.sin(x)**2) + (np.cos(x)**2)



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.sqrt(x)
np.sqrt(y)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069]])