In [2]:
import numpy as np 

In [3]:
a = np.array([0, 1, 2])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [6]:
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print(a)

0
1
2
[5 1 2]


In [7]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [8]:
a = np.zeros((3,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [10]:
c = np.full((3,3), 7)
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [11]:
d = np.random.random((3,3))
print(d)

[[0.5467405  0.18352949 0.74334439]
 [0.00857455 0.61560509 0.13513419]
 [0.9240688  0.90513308 0.17156734]]


In [12]:

print(np.random.random((3,3)))

[[0.61098145 0.0487766  0.01575107]
 [0.24199817 0.46754182 0.36261105]
 [0.23412178 0.12997831 0.22689443]]


In [13]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [15]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [17]:
i = np.arange(1, 8,dtype=float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [18]:
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [19]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])
z = np.array([5, 6], dtype=np.int64)
print( x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [20]:
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])

In [21]:
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [22]:
arr[arr>0 ]


array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])

In [23]:
temp = arr[:2, :2:]
temp

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [24]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [25]:
x=[[1,2,3],[4,5,6],[7,8,9]]
y=[[10,11,12],[13,14,15],[16,17,18]]
x=np.asanyarray(x)
y=np.asanyarray(y)


print(x+y)
print()
print(x*y)
print()
print(x-y)
print()



[[11 13 15]
 [17 19 21]
 [23 25 27]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]



In [26]:
print(x.max(),x.min())
print(y.max(),y.min())

9 1
18 10


In [27]:
x.sum()


45

In [28]:
y.sum()

126

In [29]:
(np.sin(x)**2) + (np.cos(x)**2)



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.sqrt(x)
np.sqrt(y)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069]])

In [31]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [32]:
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [33]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x.max(axis=0)

array([7, 8, 9])

In [35]:
x1=np.array([1,2,3])
x2=np.array([4,5,6])
np.add(x1,x2) 
np.multiply(x1,x2)
np.dot(x1,x2)



32

In [36]:
np.linalg.eigvals(x)

array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16])

In [37]:
np.linalg.inv(x)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [38]:
np.linalg.eigvals(x)

array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16])

In [39]:
np.linalg.eig(x)

(array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
print(x+1)
print()
print(x*2)
print()
print(x**3)
print()
print(np.linalg.matrix_power(x,2))
print()


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]]), array([1, 2, 3]), array([4, 5, 6])]
